import os
from dotenv import load_dotenv
load_dotenv()

PLAID_SANDBOX_URL = os.getenv("PLAID_SANDBOX_URL")
PLAID_PROD_URL = os.getenv("PLAID_PROD_URL")
PLAID_CLIENT_ID = os.getenv("PLAID_CLIENT_ID")
PLAID_SANDBOX_SECRET = os.getenv("PLAID_SANDBOX_SECRET")
PLAID_PROD_SECRET = os.getenv("PLAID_PROD_SECRET")
ALLOWED_ORIGIN = os.getenv("ALLOWED_ORIGIN")

DB_BASE_URL = os.getenv("SUPA_BASE_URL")
SUPA_ACCESS_TOKEN = os.getenv("SUPA_ACCESS_TOKEN")

SECRET_KEY = os.getenv("SECRET_KEY")
REFRESH_TOKEN_EXPIRATION_DAYS = int(os.getenv("REFRESH_TOKEN_EXPIRATION_DAYS"))
ACCESS_TOKEN_EXPIRATION_MINUTES = int(os.getenv("ACCESS_TOKEN_EXPIRATION_MINUTES"))
ALGORITHM = os.getenv("ALGORITHM")

IS_LOCAL = os.getenv("IS_LOCAL").upper() == "TRUE"
STAGE = os.getenv("STAGE")
LOCAL_DB_HOST = os.getenv("LOCAL_DB_HOST") 
LOCAL_DB_USER = os.getenv("LOCAL_DB_USER")
LOCAL_DB_PASS = os.getenv("LOCAL_DB_PASS") 
LOCAL_DB = os.getenv("LOCAL_DB") \

AIRTABLE_ACCESS_TOKEN = os.getenv("AIRTABLE_ACCESS_TOKEN")
AIRTABLE_ACCOUNTS = os.getenv("AIRTABLE_ACCOUNTS")
AIRTABLE_TRANSACTIONS = os.getenv("AIRTABLE_TRANSACTIONS")
AIRTABLE_DB_ID = os.getenv("AIRTABLE_DB_ID")