import os
from dotenv import load_dotenv
load_dotenv()

# CORS
ALLOWED_ORIGIN = os.getenv("ALLOWED_ORIGIN")

# Auth/JWT
SECRET_KEY = os.getenv("SECRET_KEY")
REFRESH_TOKEN_EXPIRATION_DAYS = int(os.getenv("REFRESH_TOKEN_EXPIRATION_DAYS"))
ACCESS_TOKEN_EXPIRATION_MINUTES = int(os.getenv("ACCESS_TOKEN_EXPIRATION_MINUTES"))
ALGORITHM = os.getenv("ALGORITHM")

# Admin Configuration
ADMIN_MASTER_PASSWORD = os.getenv("ADMIN_MASTER_PASSWORD")

# Local Database
LOCAL_DB_HOST = os.getenv("LOCAL_DB_HOST") 
LOCAL_DB_USER = os.getenv("LOCAL_DB_USER")
LOCAL_DB_PASS = os.getenv("LOCAL_DB_PASS") 
LOCAL_DB = os.getenv("LOCAL_DB")

# Airtable
AIRTABLE_ACCESS_TOKEN = os.getenv("AIRTABLE_ACCESS_TOKEN")
AIRTABLE_ACCOUNTS = os.getenv("AIRTABLE_ACCOUNTS")
AIRTABLE_TRANSACTIONS = os.getenv("AIRTABLE_TRANSACTIONS")
AIRTABLE_DB_ID = os.getenv("AIRTABLE_DB_ID")